#!/bin/bash
#
# This is a postinstallation script so the service can be configured and started when requested.

# user is expected by the systemd service file and `/opt/<user>` is its working directory,
sudo adduser --disabled-password --disabled-login --shell /usr/sbin/nologin --quiet --system --no-create-home --home /nonexistent miden-faucet

# Working folder.
if [ -d "/opt/miden-faucet-operator" ]
then
    echo "Directory /opt/miden-faucet-operator exists."
else
    mkdir -p /opt/miden-faucet-operator
fi
sudo chown -R miden-faucet-operator /opt/miden-faucet-operator

# Configuration folder
if [ -d "/etc/opt/miden-faucet-operator" ]
then
    echo "Directory /etc/opt/miden-faucet-operator exists."
else
    mkdir -p /etc/opt/miden-faucet-operator
fi
sudo chown -R miden-faucet-operator /etc/opt/miden-faucet-operator

sudo systemctl daemon-reload
