#!/bin/bash
#
###############
# Remove miden-faucet-operator installs
##############
sudo rm -rf /lib/systemd/system/miden-faucet-operator.service
sudo rm -rf /etc/opt/miden-faucet-operator
sudo deluser miden-faucet-operator
sudo systemctl daemon-reload
