name: Cargo Publish

permissions:
  contents: read

on:
  release:
    types: [published]

jobs:
  cargo-publish:
    name: Cargo publish
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == '0xMiden' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}

      - name: Log release info
        run: |
          echo "Publishing release ${{ github.event.release.tag_name }}"
          echo "Commit: $(git rev-parse HEAD)"
      - name: Update Rust toolchain
        run: |
          rustup update --no-self-update
      - name: Publish to crates.io
        run: cargo publish --workspace
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
